In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
print('Hello')

Hello


# One-hot Encoding

## Word Level One-hot Encoding

In [1]:
import numpy as np
samples = ['The cat sat on the mat', 'The dog ate my homework.']
tokenIndex = {}

for sample in samples:
    for word in sample.split():
        if word not in tokenIndex:
            tokenIndex[word] = len(tokenIndex)+1
maxLength = 10
results = np.zeros(shape = (len(samples), maxLength, max(tokenIndex.values())+1))
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split())):
        index = tokenIndex.get(word)
        results[i, j, index] = 1

results

array([[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0

## Character Level One-hot Encoding

In [2]:
import string
samples = ['The cat sat on the mat.', 'The dog ate my homework.']
characters = string.printable
tokeIndex = dict(zip(range(1, len(characters) + 1), characters))
tokenIndex
maxLength = 50
results = np.zeros((len(samples), maxLength, len(tokenIndex) + 1))
for i, sample in enumerate(samples):
    for j, character in enumerate(sample):
        index = tokenIndex.get(character)
        results[i,j,index] = 1
results[0]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.

## One-Hot Encoding for Categorical Data Using In-Built Function

In [2]:
import tensorflow as tf
categories = [0, 1, 2, 1, 3]
numCategories = 4
oneHot = tf.keras.utils.to_categorical(categories, num_classes = numCategories)
print(oneHot)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


## Wor-level One-Hot Encoding for Text Data Using BuiltIn Functions

In [23]:
from tensorflow.keras.preprocessing.text import Tokenizer
samples = ['The cat sat on the mat', 'The dog ate my homework']
tokenizer = Tokenizer(num_words = 10)
tokenizer.fit_on_texts(samples)
print(tokenizer.word_index)
print(tokenizer.word_index.keys())
sequences = tokenizer.texts_to_sequences(samples)
print(sequences)
oneHotResults = tokenizer.texts_to_matrix(samples, mode = 'binary')
print(oneHotResults)

{'the': 1, 'cat': 2, 'sat': 3, 'on': 4, 'mat': 5, 'dog': 6, 'ate': 7, 'my': 8, 'homework': 9}
dict_keys(['the', 'cat', 'sat', 'on', 'mat', 'dog', 'ate', 'my', 'homework'])
[[1, 2, 3, 4, 1, 5], [1, 6, 7, 8, 9]]
[[0. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 1. 1. 1.]]


# Word Embeddings

In [1]:
from keras.layers import Embedding
from keras.datasets import imdb
from keras import preprocessing
from keras.models import Sequential
from keras.layers import Flatten, Dense

In [5]:
maxFeatures = 10000
maxLen = 20
(xTrain, yTrain), (xTest, yTest) = imdb.load_data(num_words = maxFeatures)

xTrain = preprocessing.sequence.pad_sequences(xTrain, maxlen = maxLen)
xTest = preprocessing.sequence.pad_sequences(xTest, maxlen = maxLen)


model = Sequential()
model.add(Embedding(maxFeatures, 8, input_length = maxLen))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))
model.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy', metrics = ['accuracy'])


model.summary()

results = model.fit(xTrain, yTrain,
                   epochs = 10,
                   batch_size = 32,
                   validation_split = 0.2)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5828 - loss: 0.6815 - val_accuracy: 0.7050 - val_loss: 0.5950
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7482 - loss: 0.5452 - val_accuracy: 0.7314 - val_loss: 0.5190
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7898 - loss: 0.4588 - val_accuracy: 0.7464 - val_loss: 0.5017
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8027 - loss: 0.4322 - val_accuracy: 0.7492 - val_loss: 0.4976
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8217 - loss: 0.4021 - val_accuracy: 0.7568 - val_loss: 0.4973
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8246 - loss: 0.3899 - val_accuracy: 0.7538 - val_loss: 0.5007
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8403 - loss: 0.3691 - val_accuracy: 0.7562 - val_loss: 0.5052
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8496 - loss: 0.3567 - val_accuracy: 0.

## Working on Raw IMDB Dataset

In [4]:
import os
imdbDir = '/kaggle/input/imdb-dataset-fcohlet/aclImdb'
testDir = '/kaggle/input/imdb-dataset-fcohlet/aclImdb/test'
trainDir = '/kaggle/input/imdb-dataset-fcohlet/aclImdb/train'

In [6]:
labels = []
texts = []
embedPath = '/kaggle/input/glove-6b-zip/glove.6B.100d.txt'
