In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [31]:
from platform import python_version
import tensorflow as tf
import os
import numpy as np

In [32]:
print(f"Python version : {python_version()}")
print(f"Tensorflow Version : {tf.__version__}")
print(f"Eager Execution: {tf.executing_eagerly()}")

Python version : 3.10.13
Tensorflow Version : 2.15.0
Eager Execution: True


In [33]:
a = tf.ones((2,2))
b = tf.zeros((2,2))
print(a,b)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32) tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [34]:
out = tf.math.reduce_sum(a, axis = 1)
print(out)
c = out.get_shape()
print(c)
print(c[0])

tf.Tensor([2. 2.], shape=(2,), dtype=float32)
(2,)
2


In [35]:
a_ = tf.reshape(a, (1,4))
print(a_)
n_a = a.numpy()
print(n_a)

tf.Tensor([[1. 1. 1. 1.]], shape=(1, 4), dtype=float32)
[[1. 1.]
 [1. 1.]]


### Eager executive vs Graph Execution

In [36]:
import time
def e_matmul(mat_ea, mat_eb):
    return tf.matmul(mat_ea, mat_eb)

mat_ea = tf.random.normal((1000, 1000))
mat_eb = tf.random.normal((1000, 1000))

e_start = time.time()

result = e_matmul(mat_ea, mat_eb)

e_elapsed_time = time.time() - e_start

print(f"Total time by eager function is {e_elapsed_time: .4f}")

Total time by eager function is  0.0194


In [37]:
@tf.function
def g_matmul(mat_ga, mat_gb):
    return tf.matmul(mat_ga, mat_gb)

mat_ga = tf.random.normal((1000, 1000))
mat_gb = tf.random.normal((1000, 1000))

g_start = time.time()

result = g_matmul(mat_ga, mat_gb)

g_elapsed_time = time.time() - g_start

print(f"Total time by Graph function is {g_elapsed_time: .4f}")

Total time by Graph function is  0.0353


In [42]:
import timeit
from tensorflow.keras import Model, Input
from tensorflow.keras.layers import Dense, Flatten
model = tf.keras.Sequential()
model.add(tf.keras.Input(shape = (28, 28)))
model.add(Flatten())
model.add(Dense(256, 'relu'))
model.add(Dense(128, 'relu'))
model.add(Dense(256, 'relu'))
model.add(Dense(10, 'softmax'))

eager_model = model
X = tf.random.uniform([1000, 28, 28])
print("Eager Time", timeit.timeit(lambda: eager_model(X,training=False), number=1000))

Eager Time 13.264381928000148


In [45]:
graph_model = tf.function(model)
print("Graph time:", timeit.timeit(lambda: graph_model(X,training=False), number=1000))

Graph time: 7.42197157999999
